# Generated by Django 3.2.3 on 2024-11-28 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_subscription_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodgramuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='static/avatar/', verbose_name='Аватар'),
        ),
    ]
