# Generated by Django 3.2.3 on 2024-11-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_foodgramuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodgramuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/image', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='foodgramuser',
            name='is_subscribed',
            field=models.BooleanField(default=False, verbose_name='В подписках'),
        ),
    ]
